// <auto-generated />
namespace notomyk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class collection_for_replies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(collection_for_replies));
        
        string IMigrationMetadata.Id
        {
            get { return "201708012154216_collection_for_replies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
