// <auto-generated />
namespace notomyk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class votingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(votingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711022122274_votingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
